name: "Activity-assistant (Development)"
version: dev
slug: act_assist_dev
description: "Record, evaluate and predict Activities of Daily living (ADL). Note, this is a development container!"
url: "https://github.com/tcsvn/activity-assistant"
arch:
  - amd64
  - i386
startup: "application"
init: false
webui: "http://[HOST]:[PORT:8000]"
boot: "auto"
image: "tchr157/activity-assistant-{arch}"
hassio_role: default
homeassistant_api: true
hassio_api: true
ingress: true
ingress_port: 8000
panel_icon: "mdi:account-reactivate"
ports:
  8000/tcp: 8000
  433/tcp: 433
map:
  - share:rw
  - config:ro
ports_description:
  8000/tcp: "Required for mobile devices API access"
